### ISSUE TITLE
Tracking wishlist issue for opam 2.0

### ISSUE THREAD

**Issue by samoht** [ocaml/opam#2580]
I'm opening this issue to keep track of the features that would be great to have in opam 2.0 to support interesting new workflow:
- [x] do not force tests of recursive dependencies (related to #2277 and #2190)
- [ ] integrated documentation. Need state update hooks or persistent event stream.
- [x] local switches (related to #1595)
- [x] better opam query
- [x] bundle/snapshot (related to #929 and [existing hacks](https://github.com/samoht/vpnkit/blob/845dbd7c27de620bbacc78123def9942c31e0035/opam/update-upstream.sh))

**Comment by lefessan** [comment]
Why not release 2.00 as soon as possible, and add these features in later minor releases ? 
Latest release is now more than one year old, we should not delay 2.00 anymore than strictly necessary. There are already a lot of changes in 2.00, especially with compilers as packages.

**Comment by samoht** [comment]
- local packages: https://gist.github.com/samoht/54c5aaa7429a68d27fbe66515bea1c7b
- bundles: https://gist.github.com/samoht/54c5aaa7429a68d27fbe66515bea1c7b
- local switches seems to have landed in master already
- incremental builds: https://github.com/ocaml/opam/issues/2596 described something very useful to speed-up incremental rebuild of pinned packages (that we can really use with local switches + local package rebuild commands to have a nice dev workflow)

**Comment by avsm** [comment]
One quite prosaic one: more variables exposing OS constraints -- rather than just 'linux', can we grab the depext OS detection logic and make that available?  Some packages only work on Ubuntu>16.04 for example

**Comment by AltGr** [comment]
@avsm: you mean the `arch`, `os` and `distribution` tags that `depext` uses ? Even there we don't have a notion of "distribution version", though: that may be worth adding
