### ISSUE TITLE
Github actions todo list

### ISSUE THREAD

**Issue by rjbou** [ocaml/opam#4468]
* [ ] Add reftest run in `test` job for macos
* [ ] Add `cold` job for macos
* [ ] Add windows jobs
* [ ] Cache lib-ext build with key os, ocaml version, & src_ext
