### ISSUE TITLE
Remaining places where "base" message want reviewing

### ISSUE THREAD

**Issue by dra27** [ocaml/opam#4572]
This is a tracking issue for possible residual behaviour in 2.1 from opam 2.0's base packages which don't make sense in 2.1 with switch invariants.

- [x] Base packages don't recompile with upstream changes - #4569
- [x] Pinning prompts about pinning base packages - #4571
- [x] `OpamClient.fixup` - base message in there, does it just want rewording? - #4623
- [x] `OpamClient.install_t` - updating the installed automatically state of base packages. That no longer matters? - #4623
- [x] `OpamSwitchCommand.install_compiler` - "Could not resolve base install" and "base package installs". I expect these messages just need re-wording. - #4623

The remaining three items are not critical for 2.1.0. However, we should also consider:

Do we still need to care about the `compiler` flag in the same way?

**Comment by dra27** [comment]
Fixed with #4623
